package met.freehij.kareliq.utils;

import java.util.HashMap;
import java.util.Map;

public class Keys {
    public static final int KEY_NONE = 0;
    public static final int KEY_ESCAPE = 1;
    public static final int KEY_1 = 2;
    public static final int KEY_2 = 3;
    public static final int KEY_3 = 4;
    public static final int KEY_4 = 5;
    public static final int KEY_5 = 6;
    public static final int KEY_6 = 7;
    public static final int KEY_7 = 8;
    public static final int KEY_8 = 9;
    public static final int KEY_9 = 10;
    public static final int KEY_0 = 11;
    public static final int KEY_MINUS = 12;
    public static final int KEY_EQUALS = 13;
    public static final int KEY_BACK = 14;
    public static final int KEY_TAB = 15;
    public static final int KEY_Q = 16;
    public static final int KEY_W = 17;
    public static final int KEY_E = 18;
    public static final int KEY_R = 19;
    public static final int KEY_T = 20;
    public static final int KEY_Y = 21;
    public static final int KEY_U = 22;
    public static final int KEY_I = 23;
    public static final int KEY_O = 24;
    public static final int KEY_P = 25;
    public static final int KEY_LBRACKET = 26;
    public static final int KEY_RBRACKET = 27;
    public static final int KEY_RETURN = 28;
    public static final int KEY_LCONTROL = 29;
    public static final int KEY_A = 30;
    public static final int KEY_S = 31;
    public static final int KEY_D = 32;
    public static final int KEY_F = 33;
    public static final int KEY_G = 34;
    public static final int KEY_H = 35;
    public static final int KEY_J = 36;
    public static final int KEY_K = 37;
    public static final int KEY_L = 38;
    public static final int KEY_SEMICOLON = 39;
    public static final int KEY_APOSTROPHE = 40;
    public static final int KEY_GRAVE = 41;
    public static final int KEY_LSHIFT = 42;
    public static final int KEY_BACKSLASH = 43;
    public static final int KEY_Z = 44;
    public static final int KEY_X = 45;
    public static final int KEY_C = 46;
    public static final int KEY_V = 47;
    public static final int KEY_B = 48;
    public static final int KEY_N = 49;
    public static final int KEY_M = 50;
    public static final int KEY_COMMA = 51;
    public static final int KEY_PERIOD = 52;
    public static final int KEY_SLASH = 53;
    public static final int KEY_RSHIFT = 54;
    public static final int KEY_MULTIPLY = 55;
    public static final int KEY_LMENU = 56;
    public static final int KEY_SPACE = 57;
    public static final int KEY_CAPITAL = 58;
    public static final int KEY_F1 = 59;
    public static final int KEY_F2 = 60;
    public static final int KEY_F3 = 61;
    public static final int KEY_F4 = 62;
    public static final int KEY_F5 = 63;
    public static final int KEY_F6 = 64;
    public static final int KEY_F7 = 65;
    public static final int KEY_F8 = 66;
    public static final int KEY_F9 = 67;
    public static final int KEY_F10 = 68;
    public static final int KEY_NUMLOCK = 69;
    public static final int KEY_SCROLL = 70;
    public static final int KEY_NUMPAD7 = 71;
    public static final int KEY_NUMPAD8 = 72;
    public static final int KEY_NUMPAD9 = 73;
    public static final int KEY_SUBTRACT = 74;
    public static final int KEY_NUMPAD4 = 75;
    public static final int KEY_NUMPAD5 = 76;
    public static final int KEY_NUMPAD6 = 77;
    public static final int KEY_ADD = 78;
    public static final int KEY_NUMPAD1 = 79;
    public static final int KEY_NUMPAD2 = 80;
    public static final int KEY_NUMPAD3 = 81;
    public static final int KEY_NUMPAD0 = 82;
    public static final int KEY_DECIMAL = 83;
    public static final int KEY_F11 = 87;
    public static final int KEY_F12 = 88;

    private static final Map<Integer, String> keyNames = new HashMap<>();

    static {
        keyNames.put(KEY_NONE, "NONE");
        keyNames.put(KEY_ESCAPE, "ESCAPE");
        keyNames.put(KEY_1, "1");
        keyNames.put(KEY_2, "2");
        keyNames.put(KEY_3, "3");
        keyNames.put(KEY_4, "4");
        keyNames.put(KEY_5, "5");
        keyNames.put(KEY_6, "6");
        keyNames.put(KEY_7, "7");
        keyNames.put(KEY_8, "8");
        keyNames.put(KEY_9, "9");
        keyNames.put(KEY_0, "0");
        keyNames.put(KEY_MINUS, "MINUS");
        keyNames.put(KEY_EQUALS, "EQUALS");
        keyNames.put(KEY_BACK, "BACK");
        keyNames.put(KEY_TAB, "TAB");
        keyNames.put(KEY_Q, "Q");
        keyNames.put(KEY_W, "W");
        keyNames.put(KEY_E, "E");
        keyNames.put(KEY_R, "R");
        keyNames.put(KEY_T, "T");
        keyNames.put(KEY_Y, "Y");
        keyNames.put(KEY_U, "U");
        keyNames.put(KEY_I, "I");
        keyNames.put(KEY_O, "O");
        keyNames.put(KEY_P, "P");
        keyNames.put(KEY_LBRACKET, "LBRACKET");
        keyNames.put(KEY_RBRACKET, "RBRACKET");
        keyNames.put(KEY_RETURN, "RETURN");
        keyNames.put(KEY_LCONTROL, "LCONTROL");
        keyNames.put(KEY_A, "A");
        keyNames.put(KEY_S, "S");
        keyNames.put(KEY_D, "D");
        keyNames.put(KEY_F, "F");
        keyNames.put(KEY_G, "G");
        keyNames.put(KEY_H, "H");
        keyNames.put(KEY_J, "J");
        keyNames.put(KEY_K, "K");
        keyNames.put(KEY_L, "L");
        keyNames.put(KEY_SEMICOLON, "SEMICOLON");
        keyNames.put(KEY_APOSTROPHE, "APOSTROPHE");
        keyNames.put(KEY_GRAVE, "GRAVE");
        keyNames.put(KEY_LSHIFT, "LSHIFT");
        keyNames.put(KEY_BACKSLASH, "BACKSLASH");
        keyNames.put(KEY_Z, "Z");
        keyNames.put(KEY_X, "X");
        keyNames.put(KEY_C, "C");
        keyNames.put(KEY_V, "V");
        keyNames.put(KEY_B, "B");
        keyNames.put(KEY_N, "N");
        keyNames.put(KEY_M, "M");
        keyNames.put(KEY_COMMA, "COMMA");
        keyNames.put(KEY_PERIOD, "PERIOD");
        keyNames.put(KEY_SLASH, "SLASH");
        keyNames.put(KEY_RSHIFT, "RSHIFT");
        keyNames.put(KEY_MULTIPLY, "MULTIPLY");
        keyNames.put(KEY_LMENU, "LMENU");
        keyNames.put(KEY_SPACE, "SPACE");
        keyNames.put(KEY_CAPITAL, "CAPITAL");
        keyNames.put(KEY_F1, "F1");
        keyNames.put(KEY_F2, "F2");
        keyNames.put(KEY_F3, "F3");
        keyNames.put(KEY_F4, "F4");
        keyNames.put(KEY_F5, "F5");
        keyNames.put(KEY_F6, "F6");
        keyNames.put(KEY_F7, "F7");
        keyNames.put(KEY_F8, "F8");
        keyNames.put(KEY_F9, "F9");
        keyNames.put(KEY_F10, "F10");
        keyNames.put(KEY_NUMLOCK, "NUMLOCK");
        keyNames.put(KEY_SCROLL, "SCROLL");
        keyNames.put(KEY_NUMPAD7, "NUMPAD7");
        keyNames.put(KEY_NUMPAD8, "NUMPAD8");
        keyNames.put(KEY_NUMPAD9, "NUMPAD9");
        keyNames.put(KEY_SUBTRACT, "SUBTRACT");
        keyNames.put(KEY_NUMPAD4, "NUMPAD4");
        keyNames.put(KEY_NUMPAD5, "NUMPAD5");
        keyNames.put(KEY_NUMPAD6, "NUMPAD6");
        keyNames.put(KEY_ADD, "ADD");
        keyNames.put(KEY_NUMPAD1, "NUMPAD1");
        keyNames.put(KEY_NUMPAD2, "NUMPAD2");
        keyNames.put(KEY_NUMPAD3, "NUMPAD3");
        keyNames.put(KEY_NUMPAD0, "NUMPAD0");
        keyNames.put(KEY_DECIMAL, "DECIMAL");
        keyNames.put(KEY_F11, "F11");
        keyNames.put(KEY_F12, "F12");
    }

    public static String getKeyName(int keyCode) {
        return keyNames.getOrDefault(keyCode, "UNKNOWN");
    }
}
